### ISSUE TITLE
Two Pacman Folders

### ISSUE THREAD

**Issue by WillRhoden** [ChaseManseth/SUPER-PAC#1]
In the test branch there are two folders named pacman. When downloading these, they combine and leave us with mixed files. We need to delete one of the folders. I dont know how to use github to do that.

**Comment by Rafnel** [comment]
Throw away the one that was uploaded the longest ago

**Comment by WillRhoden** [comment]
Yeah but I don't know how to delete it, they merge when I download it

**Comment by Rafnel** [comment]
O rip

**Comment by Rafnel** [comment]
I'll upload the newest version which I have on a new test branch lel

**Comment by WillRhoden** [comment]
Google tells me we can use commands to do it, but Idk how to access that

**Comment by WillRhoden** [comment]
like git -rm or something
